### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by arithmetric** [comment]
@linusnorton Thanks for merging this fix. Would you be able to publish a new version to npm with this change, as it will solve this critical install issue for Grunt 1.x users:

```
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-parallel-behat@0.4.1 wants grunt@~0.4.0
```

Thanks!

**Comment by linusnorton** [comment]
Hi,

That should be published as 0.4.2 now.

**Comment by arithmetric** [comment]
Thanks @linusnorton! I appreciate it.

**Comment by linusnorton** [comment]
Don't thank me just yet - the build failed. I'll take a look and push another version if necessary

**Comment by linusnorton** [comment]
I've updated the grunt dependencies to version 1.0 and node dependency to 4.0 and it's happy again. I hope that doesn't cause a problem, I've published as 0.4.3 but in retrospect it probably should have been a bigger jump

**Pull request merged**
