### PR TITLE
Fix to JUnit XML formatting options

### LINKED ISSUE #4: Error when adding out path
When i add an out path it throws an error: flags: '--profile=<%= envOptions.behat.profile %> --format=junit --out=./reports/behat/'

Fatal error: Cannot call method 'indexOf' of undefined

### PR DESCRIPTION
**Pull request by generalconsensus**
Added the ability to use jUnit xml tests with Behat, altered the Grunt configuration to allow junit as a separate flag with the output folder as a single variable, switched the placement of the flags to the end of the command execution.

Fixes #4

### CODE REVIEW

**Comment by linusnorton** [comment]
@generalconsensus thank you for your pull request. Would it be possible to make the tests pass? You can run them with `grunt test`

**Comment by generalconsensus** [comment]
@linusnorton what node version should I be building for -- I see that Travis CI is making me test on 0.8.28, however I see that the current stable version of node is v5.5.0. I might be new to contributing to node/grunt projects but I'm not new to contributing.

Thanks!

**Comment by generalconsensus** [comment]
After my fix for xml2js the acorn issue is gone since Travis is now selecting nodejs .10. I see the issue you mean with the grunt test, I'll try to patch that as well

**Comment by linusnorton** [comment]
I modified the travis.yml on master so it only goes with 0.10 although that is quite out of date now. Thanks again, once we get this merged we can bump the version number in npm too.

**Comment by generalconsensus** [comment]
@linusnorton I made some changes to the way that spacing is handled in the tests and through the saved array of tests for consistency

**Comment by generalconsensus** [comment]
@linusnorton how do I start using this latest version in code? I don't see it when I pull down 

```
    "grunt-parallel-behat": "~0.3.6",
```

**Comment by linusnorton** [comment]
I've bumped the version number to 0.4.0 and published. Thanks again

**Pull request merged**
